= Analysis of algorithms 
:toc: left
:stem: latexmath

* In computer science, the *analysis of algorithms* is the process of finding
  the computational complexity of algorithms -- the amount of time, storage,
  or other resources needed to execute them.
* Usually, this involves determining a function that relates the size of an
  algorithm's input to the number of steps it takes (its time complexity) or
  the number of storage locations it uses (its space complexity).
* An algorithm is said to be efficient when this function's values are small,
  or grow slowly compared to a growth in the size of the input.
* Different inputs of the same size may cause the algorithm to have different
  behavior, so best, worst and average case descriptions might all be of
  practical interest.
* When not otherwise specified, the function describing the performance of an
  algorithm is usually an upper bound, determined from the worst case inputs
  to the algorithm.

'''

* The term "analysis of algorithms" was coined by Donald Knuth.
* Algorithm analysis is an important part of a broader computational
  complexity theory, which provides theoretical estimates for the resources
  needed by any algorithm which solves a given computational problem.
* These estimates provide an insight into reasonable directions of search for
  efficient algorithms.

'''

* In theoretical analysis of algorithms it is common to estimate their
  complexity in the asymptotic sense, i.e., to estimate the complexity
  function for arbitrarily large input.
* Big O notation, Big-omega notation and Big-theta notation are used to this
  end.
* For instance, binary search is said to run in a number of steps proportional
  to the logarithm of the size stem:[n] of the sorted list being searched, or
  in stem:[O(\log n)], colloquially "in logarithmic time".
* Usually asymptotic estimates are used because different implementations of
  the same algorithm may differ in efficiency.
* However the efficiencies of any two "reasonable" implementations of a given
  algorithm are related by a constant multiplicative factor called a _hidden
  constant_.

'''

* Exact (not asymptotic) measures of efficiency can sometimes be computed but
  they usually require certain assumptions concerning the particular
  implementation of the algorithm, called a model of computation.
* A model of computation may be defined in terms of an abstract computer, e.g.
  Turing machine, and/or by postulating that certain operations are executed
  in unit time.
* For example, if the sorted list to which we apply binary search has stem:[n]
  elements, and we can guarantee that each lookup of an element in the list
  can be done in unit time, then at most stem:[\log_2(n) + 1] time units are
  needed to return an answer.

== Cost models

* Time efficiency estimates depend on what we define to be a step.
* For the analysis to correspond usefully to the actual run-time, the time
  required to perform a step must be guaranteed to be bounded above by a
  constant.
* One must be careful here; for instance, some analyses count an addition of
  two numbers as one step.
* This assumption may not be warranted in certain contexts.
* For example, if the numbers involved in a computation may be arbitrarily
  large, the time required by a single addition can no longer be assumed to be
  constant.

'''

* Two cost models are generally used:
** the *uniform cost model*, also called *unit-cost model* (and similar
   variations), assigns a constant cost to every machine operation, regardless
   of the size of the numbers involved
** the *logarithmic cost model*, also called *logarithmic-cost measurement*
   (and similar variations), assigns a cost to every machine operation
   proportional to the number of bits involved 

* The latter is more cumbersome to use, so it is only employed when necessary,
  for example in the analysis of arbitrary-precision arithmetic algorithms,
  like those used in cryptography.

'''

* A key point which is often overlooked is that published lower bounds for
  problems are often given for a model of computation that is more restricted
  than the set of operations that you could use in practice and therefore there
  are algorithms that are faster than what would naively be thought possible.

== Run-time analysis

* Run-time analysis is a theoretical classification that estimates and
  anticipates the increase in running time (or run-time or execution time) of
  an algorithm as its input size (usually denoted as stem:[n]) increases.
* Run-time efficiency is a topic of great interest in computer science: A
  program can take seconds, hours, or even years to finish executing,
  depending on which algorithm it implements.
* While software profiling techniques can be used to measure an algorithm's
  run-time in practice, they cannot provide timing data for all infinitely
  many possible inputs; the latter can only be achieved by the theoretical
  methods of run-time analysis.

=== Shortcomings of empirical metrics

* Since algorithms are platform-independent (i.e. a given algorithm can be
  implemented in an arbitrary programming language on an arbitrary computer
  running an arbitrary operating system), there are additional significant
  drawbacks to using an empirical approach to gauge the comparative
  performance of a given set of algorithms.

=== Orders of growth

* _Main article: Big O notation_

* Informally, an algorithm can be said to exhibit a growth rate on the order
  of a mathematical function if beyond a certain input size stem:[n], the function
  stem:[f(n)] times a positive constant provides an upper bound or limit for the
  run-time of that algorithm.
* In other words, for a given input size stem:[n] greater than some stem:[n_0]
  and a constant stem:[c], the run-time of that algorithm will never be larger
  than stem:[c \times f(n)].
* This concept is frequently expressed using Big O notation.
* For example, since the run-time of insertion sort grows quadratically as its
  input size increases, insertion sort can be said to be of order
  stem:[O(n^2)].

'''

* Big O notation is a convenient way to express the worst-case scenario for a
  given algorithm, although it can also be used to express the average-case --
  for example, the worst-case scenario for quicksort is stem:[O(n^2)], but the
  average-case run-time is stem:[O(n \log n)].

=== Empirical orders of growth

* Assuming the run-time follows power rule, stem:[t \approx kn^a], the
  coefficient stem:[a] can be found by taking empirical measurements of
  run-time stem:[\{t_1, t_2\}] at some problem-size points stem:[\{n_1,
  n_2\}], and calculating stem:[t_2/t_1 = (n_2/n_1)^a] so that stem:[a =
  \log(t_2/t_1)/\log(n_2/n_1)].
* In other words, this measures the slope of the empirical line on the log-log
  plot of run-time vs. input size, at some size point.
* If the order of growth indeed follows the power rule (and so the line on the
  log-log plot is indeed a straight line), the empirical value of will stay
  constant at different ranges, and if not, it will change (and the line is a
  curved line) -- but still could serve for comparison of any two given
  algorithms as to their _empirical local orders of growth behaviour_.

'''

* It is clearly seen that the first algorithm exhibits a linear order of
  growth indeed following the power rule.
* The empirical values for the second one are diminishing rapidly, suggesting
  it follows another rule of growth and in any case has much lower local
  orders of growth (and improving further still), empirically, than the first
  one.

=== Evaluating run-time complexity

* The run-time complexity for the worst-case scenario of a given algorithm can
  sometimes be evaluated by examining the structure of the algorithm and
  making some simplifying assumptions.
* Consider the following pseudocode:
+
[subs=quotes]
....
1    _get a positive integer n from input_
2    *if* n > 10
3        *print* "This might take a while..."
4    *for* i = 1 *to* n
5        *for* j = 1 *to* i
6            *print* i * j
7    *print* "Done!"
....

* A given computer will take a discrete amount of time to execute each of the
  instructions involved with carrying out this algorithm.
* Say that the actions carried out in step 1 are considered to consume time at
  most _T~1~_, step 2 uses time at most _T~2~_, and so forth.

'''

* In the algorithm above, steps 1, 2 and 7 will only be run once.
* For a worst-case evaluation, it should be assumed that step 3 will be run as
  well.
* Thus the total amount of time to run steps 1-3 and step 7 is:
+
[stem]
++++
T_1 + T_2 + T_3 + T_7
++++

* The loops in steps 4, 5 and 6 are trickier to evaluate.
* The outer loop test in step 4 will execute ( _n_ + 1 ) times, which will
  consume _T~4~_( _n_ + 1 ) time.
* The inner loop, on the other hand, is governed by the value of _j_, which
  iterates from 1 to _i_.
* On the first pass through the outer loop, _j_ iterates from 1 to 1: The
  inner loop makes one pass, so running the inner loop body (step 6) consumes
  _T~6~_ time, and the inner loop test (step 5) consumes 2_T~5~_ time.
* During the next pass through the outer loop, j iterates from 1 to 2: the
  inner loop makes two passes, so running the inner loop body (step 6)
  consumes 2_T~6~_ time, and the inner loop test (step 5) consumes 3_T~5~_
  time.

'''

* Altogether, the total time required to run the inner loop body can be
  expressed as an arithmetic progression:
+
[stem]
++++
T_6 + 2T_6 + 3T_6 + \cdots + (n - 1)T_6 + nT_6
++++
+
which can be factored as
+
[stem]
++++
[1 + 2 + 3 + \cdots + (n - 1) + n]T_6 = \left[{1 \over 2}(n^2 + n)\right]T_6
++++

* The total time required to run the inner loop test can be evaluated
  similarly:
+
[stem]
++++
\begin{aligned}
&2T_5 + 3T_5 + 4T_5 + \cdots + (n - 1)T_5 + nT_5 + (n + 1)T_5 \\
&= T_5 + 2T_5 + 3T_5 + 4T_5 + \cdots + (n-1)T_5 + nT_5 + (n+1)T_5 -T_5 \\
++++
+
which can be factored as
+
[stem]
++++
&T_5[1 + 2 + 3 + \cdots + (n - 1) + n + (n + 1)] - T_5 \\
&= \left[{1 \over 2}(n^2 + n)\right]T_5 + (n + 1)T_5 - T_5 \\
&= \left[{1 \over 2}(n^2 + n)\right]T_5 + nT_5 \\
&= \left[{1 \over 2}(n^2 + 3n)\right]T_5
\end{aligned}
++++

* Therefore, the total run-time for this algorithm is:
+
[stem]
++++
f(n) = T_1 + T_2 + T_3 + T_7 + (n + 1)T_4 + \left[{1 \over 2}(n^2 +
n)\right]T_6 + \left[{1 \over 2}(n^2 + 3n)\right]T_5
++++
+
which reduces to
+
[stem]
++++
f(n) = \left[{1 \over 2}(n^2 + n)\right]T_6 + \left[{1 \over 2}(n^2 +
3n)\right]T_5 + (n + 1)T_4 + T_1 + T_2 + T_3 + T_7
++++

* As a rule-of-thumb, one can assume that the highest-order term in any given
  function dominates its rate of growth and thus defines its run-time order.
* In this example, n^2^ is the highest-order term, so one can conclude that
  stem:[f(n) = O(n^2^)].
* Formally this can be proven as follows:
+
****
Prove that stem:[\left[{1 \over 2}(n^2 + n)\right]T_6 + \left[{1 \over 2}(n^2
+ 3n)\right]T_5 + (n + 1)T_4 + T_1 + T_2 + T_3 + T_7 < cn^2, n \ge n_0]

[stem]
++++
\begin{aligned}
&\left[{1 \over 2}(n^2 + n)\right]T_6 + \left[{1 \over 2}(n^2 + 3n)\right]T_5 +
(n + 1)T_4 + T_1 + T_2 + T_3 + T_7 \\
&\le (n^2 + n)T_6 + (n^2 + 3n)T_5 + (n + 1)T_4 + T_1 + T_2 + T_3 + T_7
\ (\text{for }n \ge 0)
\end{aligned}
++++

* Let _k_ be a constant greater than or equal to [_T~1~_.._T~7~_]

[stem]
++++
\begin{aligned}
&T_6(n^2 + n) + T_5(n^2 + 3n) + (n + 1)T_4 + T_1 + T_2 + T_3 + T_7 \le k(n^2 + n) + k(n^2 + 3n) + kn + 5k \\
&= 2kn^2 + 5kn + 5k \leq 2kn^2 + 5kn^2 + 5kn^2\ (\text{for }n \ge 1) =12kn^2
\end{aligned}
++++

* Therefore 
+
[stem]
++++
\left[{1 \over 2}(n^2 + n)\right]T_6 + \left[{1 \over 2}(n^2 + 3n)\right]T_5 +
(n+1)T_4 + T_1 + T_2 + T_3 + T_7 \le cn^2, n \ge n_0 \text{ for } c = 12k, n_0
= 1
++++
****

* A more elegant approach to analyzing this algorithm would be to declare that
  [_T~1~_.._T~7~_] are all equal to one unit of time, in a system of units
  chosen so that one unit is greater than or equal to the actual times for
  these steps.
* This would mean that the algorithm's run-time breaks down as follows:
+
[stem]
++++
4 + \sum_{i = 1}^n i \le 4 + \sum_{i = 1}^n n = 4 + n^2 \le 5n^2\ ({\text{for
}}n \ge 1) = O(n^2).
++++

=== Growth rate analysis of other resources

* The methodology of run-time analysis can also be utilized for predicting
  other growth rates, such as consumption of memory space.
* As an example, consider the following pseudocode which manages and
  reallocates memory usage by a program based on the size of a file which that
  program manages:
+
[subs=quotes]
....
*while* _file is still open_:
    *let* n = _size of file_
    *for* _every 100,000 kilobytes of increase in file size_
        _double the amount of memory reserved_
....

* In this instance, as the file size n increases, memory will be consumed at
  an exponential growth rate, which is order stem:[O(2^n)].
* This is an extremely rapid and most likely unmanageable growth rate for
  consumption of memory resources.

== Relevance

* Algorithm analysis is important in practice because the accidental or unintentional use of an inefficient algorithm can significantly impact system performance.
* In time-sensitive applications, an algorithm taking too long to run can render its results outdated or useless.
* An inefficient algorithm can also end up requiring an uneconomical amount of computing power or storage in order to run, again rendering it practically useless.

== Constant factors

* Analysis of algorithms typically focuses on the asymptotic performance,
  particularly at the elementary level, but in practical applications constant
  factors are important, and real-world data is in practice always limited in
  size.
* The limit is typically the size of addressable memory, so on 32-bit machines
  2^32^ = 4 GiB (greater if segmented memory is used) and on 64-bit machines
  2^64^ = 16 EiB.
* Thus given a limited size, an order of growth (time or space) can be
  replaced by a constant factor, and in this sense all practical algorithms
  are O(1) for a large enough constant, or for small enough data.

'''

* This interpretation is primarily useful for functions that grow extremely
  slowly: (binary) iterated logarithm (log*) is less than 5 for all practical
  data (2^65536^ bits); (binary) log-log (log log _n_) is less than 6 for virtually
  all practical data (2^64^ bits); and binary log (log _n_) is less than 64 for
  virtually all practical data (2^64^ bits).
* An algorithm with non-constant complexity may nonetheless be more efficient
  than an algorithm with constant complexity on practical data if the overhead
  of the constant time algorithm results in a larger constant factor, e.g., one
  may have stem:[K > k\log \log n] so long as stem:[K / k > 6] and stem:[n <
  2^{2^6} = 2^{64}].

'''

* For large data linear or quadratic factors cannot be ignored, but for small
  data an asymptotically inefficient algorithm may be more efficient.
* This is particularly used in hybrid algorithms, like Timsort, which use an
  asymptotically efficient algorithm (here merge sort, with time complexity
  stem:[n\log n]), but switch to an asymptotically inefficient algorithm (here
  insertion sort, with time complexity stem:[n^2]) for small data, as the
  simpler algorithm is faster on small data.

== References

* Cormen, Thomas H.; Leiserson, Charles E.; Rivest, Ronald L. & Stein,
  Clifford (2001). _Introduction to Algorithms_. Chapter 1: Foundations
  (Second ed.). Cambridge, MA: MIT Press and McGraw-Hill. pp. 3-122. ISBN
  0-262-03293-7.
* Sedgewick, Robert (1998). _Algorithms in C_, Parts 1-4: Fundamentals, Data
  Structures, Sorting, Searching (3rd ed.). Reading, MA: Addison-Wesley
  Professional. ISBN 978-0-201-31452-6.
