= BIOS

* In computing, *BIOS* (/ˈbaɪɒs, -oʊs/, *Basic Input/Output System*, also
  known as the *System BIOS*, *ROM BIOS*, *BIOS ROM* or *PC BIOS*) is a type
  of firmware used to provide runtime services for operating systems and
  programs and to perform hardware initialization during the booting process
  (power-on startup).
* The firmware comes pre-installed on the computer's motherboard.

'''

* The name originates from the Basic Input/Output System used in the CP/M
  operating system in 1975.
* The BIOS firmware was originally proprietary to the IBM PC; it was reverse
  engineered by some companies (such as Phoenix Technologies) looking to
  create compatible systems.
* The interface of that original system serves as a de facto standard.

'''

* The BIOS in older PCs initializes and tests the system hardware components
  (power-on self-test or POST for short), and loads a boot loader from a mass
  storage device which then initializes a kernel.
* In the era of DOS, the BIOS provided BIOS interrupt calls for the keyboard,
  display, storage, and other input/output (I/O) devices that standardized an
  interface to application programs and the operating system.
* More recent operating systems do not use the BIOS interrupt calls after
  startup.

'''

* Most BIOS implementations are specifically designed to work with a
  particular computer or motherboard model, by interfacing with various
  devices especially system chipset.
* Originally, BIOS firmware was stored in a ROM chip on the PC motherboard.
* In later computer systems, the BIOS contents are stored on flash memory so
  it can be rewritten without removing the chip from the motherboard.
* This allows easy, end-user updates to the BIOS firmware so new features can
  be added or bugs can be fixed, but it also creates a possibility for the
  computer to become infected with BIOS rootkits.
* Furthermore, a BIOS upgrade that fails could brick the motherboard.

'''

* Unified Extensible Firmware Interface (UEFI) is a successor to the legacy PC
  BIOS, aiming to address its technical limitations.
* UEFI firmware may include legacy BIOS compatibility to maintain
  compatibility with operating systems and option cards that do not support
  UEFI native operation.
* Since 2020, all PCs for Intel platforms no longer support Legacy BIOS.
* The last version of Microsoft Windows to officially support running on PCs
  which use legacy BIOS firmware is Windows 10 as Windows 11 requires a
  UEFI-compliant system (except for IoT Enterprise editions of Windows 11 since
  version 24H2).
